
app = 'my-blog-application' # Change this
primary_region = 'iad'

[build]

[env]
  DB_PATH = '/data/blog.db'
  MEDIA_ROOT = '/data/media'

[[mounts]]
  source = 'blog_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
