"""add rss enabled to settings

Revision ID: 7384403adc46
Revises: d6851f10fb6b
Create Date: 2025-03-02 22:56:09.461325

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7384403adc46"
down_revision: Union[str, None] = "d6851f10fb6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("rss_enabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "rss_enabled")
    # ### end Alembic commands ###
