"""add published at field

Revision ID: 891c36019a4e
Revises: 2b65b4b8c9f6
Create Date: 2025-03-25 20:11:05.298989

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "891c36019a4e"
down_revision: Union[str, None] = "2b65b4b8c9f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("published_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE posts SET published_at = created_at")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "published_at")
    # ### end Alembic commands ###
